//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.9151
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class PASSPORTSCAN
{

    private RESERVATION[] rESERVATIONField;

    private Guests[] guestsField;

    /// <remarks/>
    /// /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RESERVATION")]
    public RESERVATION[] RESERVATION
    {
        get
        {
            return this.rESERVATIONField;
        }
        set
        {
            this.rESERVATIONField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Guests")]
    public Guests[] Guests
    {
        get
        {
            return this.guestsField;
        }
        set
        {
            this.guestsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RESERVATION
{

    private string pmsIDField;

    private string groupNameField;

    private string arrivalField;

    private string departureField;

    private string roomField;

    private string roomTypeField;

    private string rateField;

    private string adultField;

    private string childField;

    /// <remarks/>
    public string PmsID
    {
        get
        {
            return this.pmsIDField;
        }
        set
        {
            this.pmsIDField = value;
        }
    }

    /// <remarks/>
    public string GroupName
    {
        get
        {
            return this.groupNameField;
        }
        set
        {
            this.groupNameField = value;
        }
    }

    /// <remarks/>
    public string Arrival
    {
        get
        {
            return this.arrivalField;
        }
        set
        {
            this.arrivalField = value;
        }
    }

    /// <remarks/>
    public string Departure
    {
        get
        {
            return this.departureField;
        }
        set
        {
            this.departureField = value;
        }
    }

    /// <remarks/>
    public string Room
    {
        get
        {
            return this.roomField;
        }
        set
        {
            this.roomField = value;
        }
    }

    /// <remarks/>
    public string RoomType
    {
        get
        {
            return this.roomTypeField;
        }
        set
        {
            this.roomTypeField = value;
        }
    }

    /// <remarks/>
    public string Rate
    {
        get
        {
            return this.rateField;
        }
        set
        {
            this.rateField = value;
        }
    }

    /// <remarks/>
    public string Adult
    {
        get
        {
            return this.adultField;
        }
        set
        {
            this.adultField = value;
        }
    }

    /// <remarks/>
    public string Child
    {
        get
        {
            return this.childField;
        }
        set
        {
            this.childField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class Guests
{

    private string pmsIDField;

    private string guestsTypeField;

    private string titleField;

    private string firstNameField;

    private string lastNameField;

    private string middleNameField;

    private string sexField;

    private string nationalityField;

    private string birthNationField;

    private string nationField;

    private string birthDateField;

    private string issueDateField;

    private string expirationField;

    private string docTypeField;

    private string docNumberField;

    private string birthPlaceField;

    private string birthProvinceField;

    private string issuePlaceField;

    private string issueProvinceField;

    private string address1Field;

    private string address2Field;

    private string address3Field;

    private string cityField;

    private string provinceField;

    private string stateField;

    private string eMailField;

    private string mobileField;

    private string sign0Field;

    private string sign1Field;

    private string sign2Field;

    private string sign3Field;

    /// <remarks/>
    public string PmsID
    {
        get
        {
            return this.pmsIDField;
        }
        set
        {
            this.pmsIDField = value;
        }
    }

    /// <remarks/>
    public string GuestsType
    {
        get
        {
            return this.guestsTypeField;
        }
        set
        {
            this.guestsTypeField = value;
        }
    }

    /// <remarks/>
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string FirstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    public string LastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
        }
    }

    /// <remarks/>
    public string MiddleName
    {
        get
        {
            return this.middleNameField;
        }
        set
        {
            this.middleNameField = value;
        }
    }

    /// <remarks/>
    public string Sex
    {
        get
        {
            return this.sexField;
        }
        set
        {
            this.sexField = value;
        }
    }

    /// <remarks/>
    public string Nationality
    {
        get
        {
            return this.nationalityField;
        }
        set
        {
            this.nationalityField = value;
        }
    }

    /// <remarks/>
    public string BirthNation
    {
        get
        {
            return this.birthNationField;
        }
        set
        {
            this.birthNationField = value;
        }
    }

    /// <remarks/>
    public string Nation
    {
        get
        {
            return this.nationField;
        }
        set
        {
            this.nationField = value;
        }
    }

    /// <remarks/>
    public string BirthDate
    {
        get
        {
            return this.birthDateField;
        }
        set
        {
            this.birthDateField = value;
        }
    }

    /// <remarks/>
    public string IssueDate
    {
        get
        {
            return this.issueDateField;
        }
        set
        {
            this.issueDateField = value;
        }
    }

    /// <remarks/>
    public string Expiration
    {
        get
        {
            return this.expirationField;
        }
        set
        {
            this.expirationField = value;
        }
    }

    /// <remarks/>
    public string DocType
    {
        get
        {
            return this.docTypeField;
        }
        set
        {
            this.docTypeField = value;
        }
    }

    /// <remarks/>
    public string DocNumber
    {
        get
        {
            return this.docNumberField;
        }
        set
        {
            this.docNumberField = value;
        }
    }

    /// <remarks/>
    public string BirthPlace
    {
        get
        {
            return this.birthPlaceField;
        }
        set
        {
            this.birthPlaceField = value;
        }
    }

    /// <remarks/>
    public string BirthProvince
    {
        get
        {
            return this.birthProvinceField;
        }
        set
        {
            this.birthProvinceField = value;
        }
    }

    /// <remarks/>
    public string IssuePlace
    {
        get
        {
            return this.issuePlaceField;
        }
        set
        {
            this.issuePlaceField = value;
        }
    }

    /// <remarks/>
    public string IssueProvince
    {
        get
        {
            return this.issueProvinceField;
        }
        set
        {
            this.issueProvinceField = value;
        }
    }

    /// <remarks/>
    public string Address1
    {
        get
        {
            return this.address1Field;
        }
        set
        {
            this.address1Field = value;
        }
    }

    /// <remarks/>
    public string Address2
    {
        get
        {
            return this.address2Field;
        }
        set
        {
            this.address2Field = value;
        }
    }

    /// <remarks/>
    public string Address3
    {
        get
        {
            return this.address3Field;
        }
        set
        {
            this.address3Field = value;
        }
    }

    /// <remarks/>
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    public string Province
    {
        get
        {
            return this.provinceField;
        }
        set
        {
            this.provinceField = value;
        }
    }

    /// <remarks/>
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    public string EMail
    {
        get
        {
            return this.eMailField;
        }
        set
        {
            this.eMailField = value;
        }
    }

    /// <remarks/>
    public string Mobile
    {
        get
        {
            return this.mobileField;
        }
        set
        {
            this.mobileField = value;
        }
    }

    /// <remarks/>
    public string Sign0
    {
        get
        {
            return this.sign0Field;
        }
        set
        {
            this.sign0Field = value;
        }
    }

    /// <remarks/>
    public string Sign1
    {
        get
        {
            return this.sign1Field;
        }
        set
        {
            this.sign1Field = value;
        }
    }

    /// <remarks/>
    public string Sign2
    {
        get
        {
            return this.sign2Field;
        }
        set
        {
            this.sign2Field = value;
        }
    }

    /// <remarks/>
    public string Sign3
    {
        get
        {
            return this.sign3Field;
        }
        set
        {
            this.sign3Field = value;
        }
    }
}
