//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.9151
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EricsoftGuestData {
    
    private EricsoftGuestDataHeader headerField;
    
    private EricsoftGuestDataBody bodyField;
    
    /// <remarks/>
    public EricsoftGuestDataHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBody Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataHeader {
    
    private string sourceGeneratorField;
    
    private System.DateTime dateField;
    
    /// <remarks/>
    public string SourceGenerator {
        get {
            return this.sourceGeneratorField;
        }
        set {
            this.sourceGeneratorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBody {
    
    private string surnameField;
    
    private string nameField;
    
    private EricsoftGuestDataBodyResidence residenceField;
    
    private EricsoftGuestDataBodyBirthData birthDataField;
    
    private EricsoftGuestDataBodyNationality nationalityField;
    
    private EricsoftGuestDataBodyIdentificationDocument identificationDocumentField;
    
    private EricsoftGuestDataBodyAuthorization authorizationField;
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyResidence Residence {
        get {
            return this.residenceField;
        }
        set {
            this.residenceField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyBirthData BirthData {
        get {
            return this.birthDataField;
        }
        set {
            this.birthDataField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyNationality Nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyIdentificationDocument IdentificationDocument {
        get {
            return this.identificationDocumentField;
        }
        set {
            this.identificationDocumentField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyAuthorization Authorization {
        get {
            return this.authorizationField;
        }
        set {
            this.authorizationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyResidence {
    
    private string addressField;
    
    private EricsoftGuestDataBodyResidenceCity cityField;
    
    private EricsoftGuestDataBodyResidenceNation nationField;
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyResidenceCity City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyResidenceNation Nation {
        get {
            return this.nationField;
        }
        set {
            this.nationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyResidenceCity {
    
    private string nameField;
    
    private ushort zipField;
    
    private object districtField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public ushort Zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
    
    /// <remarks/>
    public object District {
        get {
            return this.districtField;
        }
        set {
            this.districtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyResidenceNation {
    
    private string identificationCodeField;
    
    /// <remarks/>
    public string IdentificationCode {
        get {
            return this.identificationCodeField;
        }
        set {
            this.identificationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyBirthData {
    
    private System.DateTime dateField;
    
    private EricsoftGuestDataBodyBirthDataCity cityField;
    
    private EricsoftGuestDataBodyBirthDataNation nationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyBirthDataCity City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyBirthDataNation Nation {
        get {
            return this.nationField;
        }
        set {
            this.nationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyBirthDataCity {
    
    private string nameField;
    
    private object districtField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public object District {
        get {
            return this.districtField;
        }
        set {
            this.districtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyBirthDataNation {
    
    private string identificationCodeField;
    
    /// <remarks/>
    public string IdentificationCode {
        get {
            return this.identificationCodeField;
        }
        set {
            this.identificationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyNationality {
    
    private EricsoftGuestDataBodyNationalityNation nationField;
    
    /// <remarks/>
    public EricsoftGuestDataBodyNationalityNation Nation {
        get {
            return this.nationField;
        }
        set {
            this.nationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyNationalityNation {
    
    private string identificationCodeField;
    
    /// <remarks/>
    public string IdentificationCode {
        get {
            return this.identificationCodeField;
        }
        set {
            this.identificationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyIdentificationDocument {
    
    private string typeField;
    
    private string numberField;
    
    private System.DateTime issueDateField;
    
    private EricsoftGuestDataBodyIdentificationDocumentCity cityField;
    
    private EricsoftGuestDataBodyIdentificationDocumentNation nationField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime IssueDate {
        get {
            return this.issueDateField;
        }
        set {
            this.issueDateField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyIdentificationDocumentCity City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public EricsoftGuestDataBodyIdentificationDocumentNation Nation {
        get {
            return this.nationField;
        }
        set {
            this.nationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyIdentificationDocumentCity {
    
    private string nameField;
    
    private object districtField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public object District {
        get {
            return this.districtField;
        }
        set {
            this.districtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyIdentificationDocumentNation {
    
    private string identificationCodeField;
    
    /// <remarks/>
    public string IdentificationCode {
        get {
            return this.identificationCodeField;
        }
        set {
            this.identificationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EricsoftGuestDataBodyAuthorization {
    
    private byte personalDataUseField;
    
    /// <remarks/>
    public byte PersonalDataUse {
        get {
            return this.personalDataUseField;
        }
        set {
            this.personalDataUseField = value;
        }
    }
}
