//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.9151
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PASSPORTSCAN {
    
    private PASSPORTSCANRESERVATION rESERVATIONField;
    
    private PASSPORTSCANGuests guestsField;
    
    /// <remarks/>
    public PASSPORTSCANRESERVATION RESERVATION {
        get {
            return this.rESERVATIONField;
        }
        set {
            this.rESERVATIONField = value;
        }
    }
    
    /// <remarks/>
    public PASSPORTSCANGuests Guests {
        get {
            return this.guestsField;
        }
        set {
            this.guestsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PASSPORTSCANRESERVATION {
    
    private uint pmsIDField;
    
    private object groupNameField;
    
    private uint arrivalField;
    
    private uint departureField;
    
    private byte roomField;
    
    private string roomTypeField;
    
    private object rateField;
    
    private byte adultField;
    
    private byte childField;
    
    /// <remarks/>
    public uint PmsID {
        get {
            return this.pmsIDField;
        }
        set {
            this.pmsIDField = value;
        }
    }
    
    /// <remarks/>
    public object GroupName {
        get {
            return this.groupNameField;
        }
        set {
            this.groupNameField = value;
        }
    }
    
    /// <remarks/>
    public uint Arrival {
        get {
            return this.arrivalField;
        }
        set {
            this.arrivalField = value;
        }
    }
    
    /// <remarks/>
    public uint Departure {
        get {
            return this.departureField;
        }
        set {
            this.departureField = value;
        }
    }
    
    /// <remarks/>
    public byte Room {
        get {
            return this.roomField;
        }
        set {
            this.roomField = value;
        }
    }
    
    /// <remarks/>
    public string RoomType {
        get {
            return this.roomTypeField;
        }
        set {
            this.roomTypeField = value;
        }
    }
    
    /// <remarks/>
    public object Rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
    
    /// <remarks/>
    public byte Adult {
        get {
            return this.adultField;
        }
        set {
            this.adultField = value;
        }
    }
    
    /// <remarks/>
    public byte Child {
        get {
            return this.childField;
        }
        set {
            this.childField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PASSPORTSCANGuests {
    
    private uint pmsIDField;
    
    private object guestsTypeField;
    
    private object titleField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private object middleNameField;
    
    private string sexField;
    
    private string nationalityField;
    
    private string birthNationField;
    
    private string nationField;
    
    private uint birthDateField;
    
    private uint issueDateField;
    
    private uint expirationField;
    
    private string docTypeField;
    
    private uint docNumberField;
    
    private object birthPlaceField;
    
    private object birthProvinceField;
    
    private object issuePlaceField;
    
    private object issueProvinceField;
    
    private object address1Field;
    
    private object address2Field;
    
    private object address3Field;
    
    private object cityField;
    
    private object provinceField;
    
    private object stateField;
    
    private object eMailField;
    
    private object mobileField;
    
    private sbyte sign0Field;
    
    private sbyte sign1Field;
    
    private byte sign2Field;
    
    private byte sign3Field;
    
    /// <remarks/>
    public uint PmsID {
        get {
            return this.pmsIDField;
        }
        set {
            this.pmsIDField = value;
        }
    }
    
    /// <remarks/>
    public object GuestsType {
        get {
            return this.guestsTypeField;
        }
        set {
            this.guestsTypeField = value;
        }
    }
    
    /// <remarks/>
    public object Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public object MiddleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string Sex {
        get {
            return this.sexField;
        }
        set {
            this.sexField = value;
        }
    }
    
    /// <remarks/>
    public string Nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
    
    /// <remarks/>
    public string BirthNation {
        get {
            return this.birthNationField;
        }
        set {
            this.birthNationField = value;
        }
    }
    
    /// <remarks/>
    public string Nation {
        get {
            return this.nationField;
        }
        set {
            this.nationField = value;
        }
    }
    
    /// <remarks/>
    public uint BirthDate {
        get {
            return this.birthDateField;
        }
        set {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    public uint IssueDate {
        get {
            return this.issueDateField;
        }
        set {
            this.issueDateField = value;
        }
    }
    
    /// <remarks/>
    public uint Expiration {
        get {
            return this.expirationField;
        }
        set {
            this.expirationField = value;
        }
    }
    
    /// <remarks/>
    public string DocType {
        get {
            return this.docTypeField;
        }
        set {
            this.docTypeField = value;
        }
    }
    
    /// <remarks/>
    public uint DocNumber {
        get {
            return this.docNumberField;
        }
        set {
            this.docNumberField = value;
        }
    }
    
    /// <remarks/>
    public object BirthPlace {
        get {
            return this.birthPlaceField;
        }
        set {
            this.birthPlaceField = value;
        }
    }
    
    /// <remarks/>
    public object BirthProvince {
        get {
            return this.birthProvinceField;
        }
        set {
            this.birthProvinceField = value;
        }
    }
    
    /// <remarks/>
    public object IssuePlace {
        get {
            return this.issuePlaceField;
        }
        set {
            this.issuePlaceField = value;
        }
    }
    
    /// <remarks/>
    public object IssueProvince {
        get {
            return this.issueProvinceField;
        }
        set {
            this.issueProvinceField = value;
        }
    }
    
    /// <remarks/>
    public object Address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    public object Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    public object Address3 {
        get {
            return this.address3Field;
        }
        set {
            this.address3Field = value;
        }
    }
    
    /// <remarks/>
    public object City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public object Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public object State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public object EMail {
        get {
            return this.eMailField;
        }
        set {
            this.eMailField = value;
        }
    }
    
    /// <remarks/>
    public object Mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    public sbyte Sign0 {
        get {
            return this.sign0Field;
        }
        set {
            this.sign0Field = value;
        }
    }
    
    /// <remarks/>
    public sbyte Sign1 {
        get {
            return this.sign1Field;
        }
        set {
            this.sign1Field = value;
        }
    }
    
    /// <remarks/>
    public byte Sign2 {
        get {
            return this.sign2Field;
        }
        set {
            this.sign2Field = value;
        }
    }
    
    /// <remarks/>
    public byte Sign3 {
        get {
            return this.sign3Field;
        }
        set {
            this.sign3Field = value;
        }
    }
}
