DROP TABLE IF EXISTS UTENZE; 
DROP TABLE IF EXISTS LOGIN;
DROP TABLE IF EXISTS LOGIN_ACCESS;
DROP TABLE IF EXISTS TEMPLATE;
DROP TABLE IF EXISTS TEMPLATE_LINQ;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS FLAG;
DROP TABLE IF EXISTS NAZIONE;
DROP TABLE IF EXISTS REGIONE;
DROP TABLE IF EXISTS PROVINCE;
DROP TABLE IF EXISTS COMUNI;
DROP TABLE IF EXISTS LOCALITA;

CREATE TABLE FIRMAINCLOUD.UTENZE (  
	KEY_UTE	 	INT AUTO_INCREMENT PRIMARY KEY,
	NOME	 	VARCHAR(30) NOT NULL,		-- Nome
	COGNOME	 	VARCHAR(30) NOT NULL,		-- Cognome
	DTINS 		VARCHAR(8)  NOT NULL,		-- Data inserimento
	DTNAS		VARCHAR(8),			-- Data Nascita	
	RAG_SOCIALE	VARCHAR(30),			-- Ragione Sociale
	TYP_UTE		VARCHAR(1),			-- Soggetto giuridico / persona fisica: 'P' Privato, 'A' Azienda
	P_IVA		VARCHAR(11),			-- PIVA Titolare  
	COD_FIS		VARCHAR(16),			-- CF Titolare 
	
	KEY_NAZ 	INT,				-- Chiave tabella nazioni
	KEY_REG 	INT,				-- Chiave tabella regioni
	KEY_PRO 	INT,				-- Chiave tabella province
	KEY_COM 	INT,				-- Chiave tabella comuni
	KEY_LOC 	INT,				-- Chiave tabella località
	
	SST 		VARCHAR(10),			-- Toponimo
	STRADA 		VARCHAR(80),			-- Strada 	
	NCN 		VARCHAR(3),				-- numero civico	                                                       	
	
	PERS1 		VARCHAR(80),
	PERS2 		VARCHAR(80),
	PERS3 		VARCHAR(80),
	PERS4 		VARCHAR(80),
	PERS5 		VARCHAR(80),
	PERS6 		VARCHAR(80),
	
	CELL	 	VARCHAR(16),			-- Telefono cellulare
	MAIL 		VARCHAR(30),
	KEY_TEMPL	INT,				-- Chiave permessi
	X_LINQ  	VARCHAR(1), 			-- Associa documento - null non associato / X associato
	DT_LINQ		VARCHAR(8),			-- Data ultima associazione
	OPER_S 		VARCHAR(16)		    	-- Operatore ultima modifica			
);

CREATE TABLE FIRMAINCLOUD.LOGIN (
	KEY_LOG 	INT AUTO_INCREMENT,
	USER_ID 	VARCHAR(80) NOT NULL, 
	PASSWORD_ID 	VARCHAR(80) NOT NULL, 
	X_PERMISSION 	VARCHAR(1),
	X_ADMIN 	VARCHAR(1),
	PRIMARY KEY(KEY_LOG,USER_ID)
);

CREATE TABLE FIRMAINCLOUD.LOGIN_ACCESS (
	KEY_LOG_ACC 	INT NOT NULL,	
	DT_LOGIN	VARCHAR(12) NOT NULL,
	PRIMARY KEY(KEY_LOG_ACC,DT_LOGIN)
);  

CREATE TABLE FIRMAINCLOUD.TEMPLATE(  
	KEY_TEMPL 	INT AUTO_INCREMENT,
	DESCR	 	VARCHAR(512) NOT NULL,		-- Nome
	PATH		VARCHAR(512) NOT NULL,		-- Path File	
	DTINS 		VARCHAR(12)  NOT NULL,		-- Data inserimento	
	X_SIGN		VARCHAR(1),	
	PRIMARY KEY(KEY_TEMPL) 
);

CREATE TABLE FIRMAINCLOUD.TEMPLATE_LINQ(  
	KEY_TEMPL_L	INT AUTO_INCREMENT,	
	KEY_UTE 	INT,						-- Chiave utenza
	KEY_TEMPL 	INT,						-- Chiave template
	DESCR	 	VARCHAR(512) NOT NULL,		-- Nome
	PATH		VARCHAR(512) NOT NULL,		-- Path File	
	DTSIGN 		VARCHAR(12)  NOT NULL,		-- Data firma
	PRIMARY KEY(KEY_TEMPL_L,KEY_UTE,KEY_TEMPL) 
);  

CREATE TABLE FIRMAINCLOUD.CONFIG ( 
	CONF_PARAM 	VARCHAR(6) NOT NULL,
	CONF_VALUE 	NVARCHAR(255),
	PRIMARY KEY(CONF_PARAM)
);  

 CREATE TABLE FIRMAINCLOUD.FLAG ( 
	KEY_FLAG	INT AUTO_INCREMENT,
	KEY_TEMPL 	VARCHAR(6),
	NAME_DOC 		VARCHAR(2048),		-- Nome Documento 
	DFLAG 		VARCHAR(2048),		-- Descrizione 
	
	TYP_FLAG	VARCHAR(1),					-- C CheckBox / T TextBox / null
	ID_FLAG		INT,						-- id del flag -- valido solo per checkbox
	X_FLAG  	VARCHAR(1),					-- Enabled flag  - null non associato / X associato -- solo se typ_flag == C 
	
	X_CORD		INT,			-- Coordinate 
	Y_CORD		INT,
	WIDTH		INT,
	N_PAGE		INT,
	PRIMARY KEY(KEY_FLAG)
);  

CREATE TABLE FIRMAINCLOUD.NAZIONE (
  ID INT NOT NULL AUTO_INCREMENT,
  COD_REG CHAR(8) NOT NULL,
  COD_ISTAT CHAR(8) NOT NULL,
  NAZIONE VARCHAR(511) NOT NULL,
  PROV CHAR(4) NOT NULL,
  CITTADINANZA CHAR(255) NOT NULL,
  CATASTO CHAR(8) NOT NULL,
  CESSATO CHAR(8) NOT NULL,
  PRIMARY KEY(ID) 
); 

CREATE TABLE FIRMAINCLOUD.REGIONE (
  ID INT(11) NOT NULL DEFAULT 0,
  ID_NAZIONE INT(11) NOT NULL,
  REGIONE VARCHAR(512) NOT NULL,
  PRIMARY KEY(ID) 
);

CREATE TABLE FIRMAINCLOUD.PROVINCE (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ID_NAZIONE INT(11) NOT NULL DEFAULT '0',
  COD_REG CHAR(8) NOT NULL,
  PROV CHAR(4) NOT NULL,
  PROVINCIA VARCHAR(511) NOT NULL DEFAULT '',
  PRIMARY KEY(ID) 
);

CREATE TABLE FIRMAINCLOUD.COMUNI (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ID_NAZIONE INT(11) NOT NULL DEFAULT 0,
  ID_PROV INT(11) NOT NULL,
  COD_REG CHAR(3) DEFAULT NULL,
  COD_ISTAT CHAR(6) DEFAULT NULL,
  COMUNE VARCHAR(511) NOT NULL,
  PROV CHAR(4) NOT NULL,
  CITTADINANZA CHAR(255) NOT NULL,
  CATASTO CHAR(4) DEFAULT NULL,
  CAP CHAR(5) DEFAULT NULL,
  PREF_TEL VARCHAR(4) DEFAULT NULL,
  LAT VARCHAR(32) NOT NULL,
  LONGIT VARCHAR(32) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE FIRMAINCLOUD.LOCALITA (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  LOCALITA VARCHAR(256) NOT NULL,
  ID_COMU INT(11) NOT NULL,
  PRIMARY KEY (ID)
);

