CREATE DATABASE NameDB;
USE NameDB; 

DROP TABLE IF EXISTS UTENZE; 
DROP TABLE IF EXISTS LOGIN;
DROP TABLE IF EXISTS LOGIN_ACCESS;
DROP TABLE IF EXISTS TEMPLATE;
DROP TABLE IF EXISTS TEMPLATE_LINQ;
DROP TABLE IF EXISTS CONFIG;
DROP TABLE IF EXISTS FLAG;
DROP TABLE IF EXISTS NAZIONE;
DROP TABLE IF EXISTS REGIONE;
DROP TABLE IF EXISTS PROVINCE;
DROP TABLE IF EXISTS COMUNI;
DROP TABLE IF EXISTS LOCALITA;
DROP TABLE IF EXISTS GUESTS;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS TEMPLATEXML;

CREATE TABLE UTENZE (  
	KEY_UTE	 	INT AUTO_INCREMENT PRIMARY KEY,
	NOME	 	VARCHAR(30) NOT NULL,		-- Nome
	COGNOME	 	VARCHAR(30) NOT NULL,		-- Cognome
	DTINS 		VARCHAR(8)  NOT NULL,		-- Data inserimento
	DTNAS		VARCHAR(8),			-- Data Nascita	
	RAG_SOCIALE	VARCHAR(30),			-- Ragione Sociale
	TYP_UTE		VARCHAR(1),			-- Soggetto giuridico / persona fisica: 'P' Privato, 'A' Azienda
	P_IVA		VARCHAR(11),			-- PIVA Titolare  
	COD_FIS		VARCHAR(16),			-- CF Titolare 
	
	KEY_NAZ 	INT,				-- Chiave tabella nazioni
	KEY_REG 	INT,				-- Chiave tabella regioni
	KEY_PRO 	INT,				-- Chiave tabella province
	KEY_COM 	INT,				-- Chiave tabella comuni
	KEY_LOC 	INT,				-- Chiave tabella località
	
	SST 		VARCHAR(10),			-- Toponimo
	STRADA 		VARCHAR(80),			-- Strada 	
	NCN 		VARCHAR(3),				-- numero civico	                                                       	
	
	PERS1 		VARCHAR(80),
	PERS2 		VARCHAR(80),
	PERS3 		VARCHAR(80),
	PERS4 		VARCHAR(80),
	PERS5 		VARCHAR(80),
	PERS6 		VARCHAR(80),
	
	CELL	 	VARCHAR(16),			-- Telefono cellulare
	MAIL 		VARCHAR(30),
	KEY_TEMPL	INT,				-- Chiave permessi
	X_LINQ  	VARCHAR(1), 			-- Associa documento - null non associato / X associato
	DT_LINQ		VARCHAR(8),			-- Data ultima associazione
	OPER_S 		VARCHAR(16)		    	-- Operatore ultima modifica			
);

CREATE TABLE LOGIN (
	KEY_LOG 	INT AUTO_INCREMENT,
	USER_ID 	VARCHAR(80) NOT NULL, 
	PASSWORD_ID 	VARCHAR(80) NOT NULL, 
	X_PERMISSION 	VARCHAR(1),
	X_ADMIN 	VARCHAR(1),
	PRIMARY KEY(KEY_LOG,USER_ID)
);

CREATE TABLE LOGIN_ACCESS (
	KEY_LOG_ACC 	INT NOT NULL,	
	DT_LOGIN	VARCHAR(12) NOT NULL,
	PRIMARY KEY(KEY_LOG_ACC,DT_LOGIN)
);  

CREATE TABLE TEMPLATE(  
	KEY_TEMPL 	INT AUTO_INCREMENT,
	DESCR	 	VARCHAR(512) NOT NULL,		-- Nome
	PATH		VARCHAR(512) NOT NULL,		-- Path File	
	DTINS 		VARCHAR(12)  NOT NULL,		-- Data inserimento	
	X_SIGN		VARCHAR(1),	
	PRIMARY KEY(KEY_TEMPL) 
);

CREATE TABLE TEMPLATE_LINQ(  
	KEY_TEMPL_L	INT AUTO_INCREMENT,	
	KEY_UTE 	INT,						-- Chiave utenza
	KEY_TEMPL 	INT,						-- Chiave template
	DESCR	 	VARCHAR(512) NOT NULL,		-- Nome
	PATH		VARCHAR(512) NOT NULL,		-- Path File	
	DTSIGN 		VARCHAR(12)  NOT NULL,		-- Data firma
	PRIMARY KEY(KEY_TEMPL_L,KEY_UTE,KEY_TEMPL) 
);  

CREATE TABLE CONFIG ( 
	CONF_PARAM 	VARCHAR(6) NOT NULL,
	CONF_VALUE 	NVARCHAR(255),
	PRIMARY KEY(CONF_PARAM)
);  

 CREATE TABLE FLAG ( 
	KEY_FLAG	INT AUTO_INCREMENT,
	KEY_TEMPL 	VARCHAR(6),
	NAME_DOC 		VARCHAR(2048),		-- Nome Documento 
	DFLAG 		VARCHAR(2048),		-- Descrizione 
	
	TYP_FLAG	VARCHAR(1),					-- C CheckBox / T TextBox / null
	ID_FLAG		INT,						-- id del flag -- valido solo per checkbox
	X_FLAG  	VARCHAR(1),					-- Enabled flag  - null non associato / X associato -- solo se typ_flag == C 
	
	X_CORD		INT,			-- Coordinate 
	Y_CORD		INT,
	WIDTH		INT,
	N_PAGE		INT,
	PRIMARY KEY(KEY_FLAG)
);  

CREATE TABLE NAZIONE (
  ID INT NOT NULL AUTO_INCREMENT,
  COD_REG CHAR(8) NOT NULL,
  COD_ISTAT CHAR(8) NOT NULL,
  NAZIONE VARCHAR(511) NOT NULL,
  PROV CHAR(4) NOT NULL,
  CITTADINANZA CHAR(255) NOT NULL,
  CATASTO CHAR(8) NOT NULL,
  CESSATO CHAR(8) NOT NULL,
  PRIMARY KEY(ID) 
); 

CREATE TABLE REGIONE (
  ID INT(11) NOT NULL DEFAULT 0,
  ID_NAZIONE INT(11) NOT NULL,
  REGIONE VARCHAR(512) NOT NULL,
  PRIMARY KEY(ID) 
);

CREATE TABLE PROVINCE (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ID_NAZIONE INT(11) NOT NULL DEFAULT '0',
  COD_REG CHAR(8) NOT NULL,
  PROV CHAR(4) NOT NULL,
  PROVINCIA VARCHAR(511) NOT NULL DEFAULT '',
  PRIMARY KEY(ID) 
);

CREATE TABLE COMUNI (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ID_NAZIONE INT(11) NOT NULL DEFAULT 0,
  ID_PROV INT(11) NOT NULL,
  COD_REG CHAR(3) DEFAULT NULL,
  COD_ISTAT CHAR(6) DEFAULT NULL,
  COMUNE VARCHAR(511) NOT NULL,
  PROV CHAR(4) NOT NULL,
  CITTADINANZA CHAR(255) NOT NULL,
  CATASTO CHAR(4) DEFAULT NULL,
  CAP CHAR(5) DEFAULT NULL,
  PREF_TEL VARCHAR(4) DEFAULT NULL,
  LAT VARCHAR(32) NOT NULL,
  LONGIT VARCHAR(32) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE LOCALITA (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  LOCALITA VARCHAR(256) NOT NULL,
  ID_COMU INT(11) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE TEMPLATEXML (
  FILE_NM VARCHAR(256) NOT NULL,
  FILE_PATH VARCHAR(256) NOT NULL,
  DTINS 	VARCHAR(12)  NOT NULL,		-- Data inserimento	
  PRIMARY KEY (FILE_NM)
);


CREATE TABLE RESERVATION (
    ID INT(11) NOT NULL AUTO_INCREMENT,
	PMSID VARCHAR(256) NOT NULL,
    GROUPNAME VARCHAR(64),
    ARRIVAL VARCHAR(12),
    DEPARTURE VARCHAR(12),
    ROOM VARCHAR(4),
    ROOMTYPE VARCHAR(2),
    RATE VARCHAR(12),
    ADULT INT,
    CHILD INT,
	PRIMARY KEY (ID)
);

CREATE TABLE GUESTS (
	ID INT(11) NOT NULL AUTO_INCREMENT,
    PMSID VARCHAR(256) NOT NULL,
    GUESTSTYPE VARCHAR(12),
    TITLE VARCHAR(64),
    FIRSTNAME VARCHAR(64),
    LASTNAME VARCHAR(64),
    MIDDLENAME VARCHAR(64),
    SEX CHAR(1),
    NATIONALITY VARCHAR(2),
    BIRTHNATION VARCHAR(2),
    NATION VARCHAR(2),
    BIRTHDATE VARCHAR(12),
    ISSUEDATE VARCHAR(12),
    EXPIRATION VARCHAR(12),
    DOCTYPE VARCHAR(12),
    DOCNUMBER VARCHAR(12),
    BIRTHPLACE VARCHAR(12),
    BIRTHPROVINCE VARCHAR(12),
    ISSUEPLACE VARCHAR(12),
    ISSUEPROVINCE VARCHAR(12),
    ADDRESS1 VARCHAR(64),
    ADDRESS2 VARCHAR(64),
    ADDRESS3 VARCHAR(64),
    CITY VARCHAR(32),
    PROVINCE VARCHAR(32),
    STATE VARCHAR(64),
    EMAIL VARCHAR(64),
    MOBILe VARCHAR(32),
    SIGN0 VARCHAR(4),
    SIGN1 VARCHAR(4),
    SIGN2 VARCHAR(4),
    SIGN3 VARCHAR(4),
PRIMARY KEY (ID)
);

